# external_tool_compensation: [0, 0, 0, 0, 0, 0]
# external_tool_compensation: [0.46, -0.17, -1.64, 0, 0, 0] # no tool
# external_tool_compensation: [1.131, -1.01, -2.5, -0.171, -0.142, 0.252] # kitchen finray + wrist camera
external_tool_compensation: [0.440, -0.431, -4.146, -0.332, -0.533, 0.188]


# cartesian_stiffness_target: [300, 300, 300, 50, 50, 50]
# cartesian_stiffness_target: [300, 300, 500, 50, 70, 50]
cartesian_stiffness_target: [0, 0, 0, 0, 0, 0]

# nullspace_stiffness_target: [5, 10, 0.0001, 0.05, 5, 0.05, 1]
nullspace_stiffness_target: [1, 0.1, 1, 0.01, 0.01, 0.01, 0.01]
# nullspace_stiffness_target: [0.00001, 0.05, 50, 0.05, 5, 0.05, 100]
